### ISSUE TITLE
Expected the enhancer to be a function

### ISSUE THREAD

**Issue by tommoor** [loggur/redux-replicate-localforage#1]
I'm getting an odd error after following all the documentation, I'm not sure if this is a compatability issue or not - hoping you can help decipher! 

![image](https://cloud.githubusercontent.com/assets/380914/13345991/219eb7d4-dc18-11e5-867c-8636a6dacd2c.png)

enhancer is being passed as 'true' by redux-replicate when the lib expects a method. My code looks like:

```javascript
import replicate from 'redux-replicate';
import localforageReplicator from 'redux-replicate-localforage';

const storeKey = 'propeller-development';
const replication = replicate(storeKey, localforageReplicator());
const store = createStore(
  reducers, 
  initialState,
  compose(
    applyMiddleware(thunk),
    DevTools.instrument(),
    replication
  )
);
...
```

**Comment by timbur** [comment]
Ah yeah I knew this problem would pop up when I saw that the 3rd `enhancer` argument was added to `redux`'s `createStore` method somewhat recently.  I was originally passing an (undocumented) 3rd argument as `true` to indicate it's creating a mocked/temporary store, which was used internally to determine the proper initialized values when using `setKey`.  I'm actually in the middle of making some improvements to `redux-replicate` (and related packages) to make it easier to hook everything into a proper database with queries, joins, etc., and `setKey` will be removed so I can remove the mocked store stuff and this won't be an issue.

However in the mean time, I just published an intermediate patch for you which should fix the temporary problem with using this with the latest `redux`.  Let me know if `v0.3.2` solves your problem!

**Comment by timbur** [comment]
Oh btw I meant `v0.3.2` of `redux-replicate`.  Sorry if that wasn't clear.  :)

**Comment by tommoor** [comment]
@timbur thanks for the fast response! I just tried the latest version and the error is no longer there, I'm actually still not seeing any persistence in the resources/indexeddb area of console so I may have another issue... possibly outside of this dependency

**Comment by tommoor** [comment]
So I put console logs in all of the methods in this lib and I'm not seeing any of them get triggered so starting to think there is still something awry in redux-replicate. Hoping to get a chance to investigate further this morning...

**Comment by timbur** [comment]
You might need to put `replication` first:
```js
const store = createStore(
  reducers, 
  initialState,
  compose(
    replication,
    applyMiddleware(thunk),
    DevTools.instrument()
  )
);
```

Or possibly second.  o_O

If that doesn't work, try selecting some keys and tell me if anything shows up in IndexedDB:
```js
const replication = replicate(storeKey, localforageReplicator({ someReducer: true }));
```

**Comment by tommoor** [comment]
It seems as though this line `localforageReplicator({ someReducer: true })` the replicate method expects an object to be the output, however for some reason it is returning another function...

I can actually get it to work by doing:

```
const replication = replicate(storeKey, localforageReplicator()());
```

**Comment by timbur** [comment]
Oh that's right.  That's part of the changes I'm in the middle of making (getting rid of the 2nd function call).  Sorry for the trouble.

**Comment by timbur** [comment]
Okay `v0.3.3` should allow the current example code to work without issue.  Hopefully this bug didn't bite too many people.  I don't think it bit anyone using the `providers` paradigm, but it definitely did for people using plain `redux`.  I know that had to be really annoying for you to track down.  Thanks for helping out with this!

The next major version will have a much better API and should change (simplify!) the way people create/read/update/delete data using `redux`.  :)

**Comment by tommoor** [comment]
All working well now, glad I could help :smile:
